### ISSUE TITLE
Error placing mui items on canvas

### ISSUE THREAD

**Issue by ChrisDawes** [HCL-TECH-SOFTWARE/leap-custom-widgets#5]
There is no visible object in the canvas grid, but previewing the form the widget does appear and seems to work.

But there is a JS error in the browser console:
![image](https://github.com/HCL-TECH-SOFTWARE/leap-custom-widgets/assets/7468648/60cc190e-bffe-45b4-9672-a664b67cc2a8)

**Comment by rlint** [comment]
I cannot reproduce this

**Comment by rlint** [comment]
This is a result of not loading the .js as a module. 
Must be
```
<script type='module' src='...'></script>
```

There could be a way to configure Vite to package things differently but this is the way it is for now.
